version: '3.3'
volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mnk96/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - backend_media:/app/media
    depends_on:
      - db
  frontend:
    image: mnk96/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static
  gateway:
    image: mnk96/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
